### ISSUE TITLE
Separate HTML, CSS, JS files 

### ISSUE THREAD

**Issue by KendallDoesCoding** [Kendall-Does-Coding-Websites/ChatGPT-AudioMonitoringTool#1]
Right now, the CSS and JS is in the HTML. Make new files and link them to the HTML using the following.

- Name CSS file, `styles.css`, and JS file `index.js`.

- Link CSS
```
<link rel="stylesheet" href="styles.css">
```

- Link JS
```
<script src="index.js"></script>
```

**Comment by abhinav2712** [comment]
@KendallDoesCoding  May I take this one? Please assign me this issue...

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding May I take this one? Please assign me this issue...

No, sorry. A pull request was already made before you requested to be assigned.

@Soumya-Kushwaha - In future, please request to be assigned before starting work but accepting your PR so dw.

**Comment by Soumya-Kushwaha** [comment]
@KendallDoesCoding alright, I'll make sure about this.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding alright, I'll make sure about this.

Thanks!
